### ISSUE TITLE
Schedule for 11th May needs to be updated to the real one

### ISSUE THREAD

**Issue by jobcrypt** [jobcrypt/dapp#32]
Schedule needs to be updated 
![image](https://user-images.githubusercontent.com/94724104/236068077-2f13bb0a-fc94-478c-a85d-37e545f6d24d.png)

See below 
![image](https://user-images.githubusercontent.com/94724104/236068271-5880cb58-f469-43ef-9189-55cdf530c8ef.png)

**Comment by Chrisdon95** [comment]
![Frame 5617](https://user-images.githubusercontent.com/60698889/236171280-6f647082-a941-47f6-a4d8-a33934725090.png)

**Comment by Chiamaka007** [comment]
done
